'use strict';

const app={state:null,selected:null,operation:null,poll:null,cameraLive:null,stateRefreshFailures:0};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const stateLabel=s=>({healthy:'Healthy',degraded:'Attention',failed:'Problem',unknown:'Unknown',disabled:'Disabled',planned:'Planned'})[s]||String(s||'Unknown');
const stateRank=s=>({healthy:0,planned:0,disabled:0,unknown:1,degraded:2,failed:3})[s]??1;
const age=stamp=>stamp?Math.max(0,(Date.now()-new Date(stamp).getTime())/1000):Infinity;
const ageText=stamp=>{const s=Math.round(age(stamp));if(!isFinite(s))return'No data yet';if(s<5)return'just now';if(s<60)return`${s}s ago`;if(s<3600)return`${Math.floor(s/60)}m ago`;return`${Math.floor(s/3600)}h ago`;};
const requestId=()=>globalThis.crypto?.randomUUID?.()||`mb-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

async function api(url,options={}){const response=await fetch(url,{...options,headers:{Accept:'application/json',...(options.headers||{})}});if(!response.ok)throw new Error(`${response.status} ${await response.text()||response.statusText}`);const type=response.headers.get('content-type')||'';return type.includes('application/json')?response.json():response;}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2500);}
function pill(state){return`<span class="state-pill ${esc(state)}">${esc(stateLabel(state))}</span>`;}
function worstSummary(object){const components=(object.components||[]).filter(c=>c.enabled);if(!components.length)return'No checks configured';const sorted=[...components].sort((a,b)=>stateRank(b.state)-stateRank(a.state));const worst=sorted[0];return worst.state==='healthy'?`${components.length} check${components.length===1?'':'s'} reporting normally`:worst.summary;}
function findObject(siteId,objectId){const site=app.state?.sites?.find(s=>s.id===siteId);return{site,object:site?.objects?.find(o=>o.id===objectId)};}

async function loadState({quiet=false}={}){let error;for(let attempt=0;attempt<2;attempt++){try{const data=await api('/api/v2/state');app.state=data;app.stateRefreshFailures=0;document.title=data.title||'MonitorBox';$('#title').textContent=data.title||'MonitorBox';$('#sync-label').textContent='Controller online';$('#sync-dot').className='live';render();if(app.selected)renderDrawer();return data;}catch(caught){error=caught;if(attempt===0){await sleep(125);continue;}}}app.stateRefreshFailures+=1;if(app.state&&app.stateRefreshFailures<2){$('#sync-label').textContent='Controller state refresh delayed';$('#sync-dot').className='';if(!quiet)toast(`Status refresh delayed: ${error.message}`);throw error;}$('#sync-label').textContent='Controller unavailable';$('#sync-dot').className='';renderOffline();if(!quiet)toast(`Status unavailable: ${error.message}`);throw error;}
function renderOffline(){const global=$('#global');global.className='global failed';$('#global-title').textContent='MonitorBox is unreachable';$('#global-copy').textContent='The dashboard could not retrieve canonical controller state.';$('#global-state').className='state-pill failed';$('#global-state').textContent='Problem';}
function render(){if(!app.state)return;const overall=app.state.overall||'unknown',global=$('#global');global.className=`global ${overall}`;$('#global-state').className=`state-pill ${overall}`;$('#global-state').textContent=stateLabel(overall);const conditions=(app.state.sites||[]).flatMap(site=>site.objects.filter(o=>stateRank(o.state)>0).map(o=>`${site.label}: ${o.label}`));$('#global-title').textContent=overall==='healthy'?'Everything is fine':overall==='failed'?'Action required':overall==='degraded'?'Something needs attention':'Monitoring state is incomplete';$('#global-copy').textContent=conditions.length?`${conditions.length} condition${conditions.length===1?'':'s'}: ${conditions.slice(0,3).join(' · ')}${conditions.length>3?'…':''}`:'All configured objects are reporting normally.';$('#sites').innerHTML=(app.state.sites||[]).map(renderSite).join('');bindCards();}
function renderSite(site){const connected=site.agents.filter(a=>a.connected).length,power=site.power?.state&&site.power.state!=='not_configured'?` · Power: ${site.power.state.replaceAll('_',' ')}`:'';return`<section class="site"><header class="site-header"><div><span class="eyebrow">Site</span><h2>${esc(site.label)}</h2></div><div class="site-meta">${pill(site.state)}<span>${connected}/${site.agents.length} agents connected${esc(power)}</span></div></header><div class="objects">${site.objects.map(object=>`<button class="card ${esc(object.state)}" data-site="${esc(site.id)}" data-object="${esc(object.id)}" type="button"><span class="card-top"><span><h3>${esc(object.label)}</h3><span class="card-type">${esc(object.kind.replaceAll('_',' '))}</span></span>${pill(object.state)}</span><span class="card-summary">${esc(worstSummary(object))}</span></button>`).join('')}</div></section>`;}
function bindCards(){document.querySelectorAll('[data-object]').forEach(node=>node.onclick=()=>openDrawer(node.dataset.site,node.dataset.object));}

function openDrawer(siteId,objectId){stopCameraLive(false);app.selected={siteId,objectId};renderDrawer();const drawer=$('#drawer');if(!drawer.open)drawer.showModal();history.replaceState(null,'',`#${encodeURIComponent(siteId)}/${encodeURIComponent(objectId)}`);}
function closeDrawer(){stopCameraLive(false);app.selected=null;$('#drawer').close();history.replaceState(null,'',location.pathname);}
function renderDrawer(){if(!app.selected||!app.state)return;const {site,object}=findObject(app.selected.siteId,app.selected.objectId);if(!site||!object)return closeDrawer();$('#drawer-eyebrow').textContent=`${site.label} · ${object.kind.replaceAll('_',' ')}`;$('#drawer-title').textContent=object.label;$('#drawer-state').className=`state-pill ${object.state}`;$('#drawer-state').textContent=stateLabel(object.state);const life=object.planned_lifecycle;const sections=[];sections.push(`<section class="detail-section"><div class="detail-state"><div><h3>Current state</h3><strong>${esc(stateLabel(object.state))}</strong><p>${esc(worstSummary(object))}</p>${object.blocked_by?.length?`<p>Dependency context: ${esc(object.blocked_by.join(', '))}</p>`:''}</div>${pill(object.underlying_state||object.state)}</div></section>`);if(life)sections.push(`<section class="detail-section"><h3>Planned lifecycle</h3><div class="power-grid"><div><b>${esc(life.intent)}</b><span>${esc(life.state.replaceAll('_',' '))}</span></div><div><b>${esc((life.pending_recovery_checks||[]).length)}</b><span>recovery checks pending</span></div><div><b>${esc(life.suppress_alerts?'Yes':'No')}</b><span>alert suppression active</span></div></div></section>`);if(object.kind==='ups')sections.push(renderPower(site,object));sections.push(renderComponents(site,object));sections.push(renderActions(site,object));if(object.kind==='camera')sections.push(renderCamera(site,object));sections.push(`<section class="detail-section"><h3>History</h3><div id="history-charts"><div class="chart-empty">Loading recent metric history…</div></div></section>`);$('#drawer-body').innerHTML=sections.join('');bindDrawer(site,object);loadCharts(site,object).catch(()=>{});}
function renderPower(site,object){const p=site.power||{},entry=Object.values(p.ups||{}).find(v=>object.components.some(c=>c.id&&c.id.includes('power')))||null;return`<section class="detail-section"><h3>Power context</h3><div class="power-grid"><div><b>${esc(p.state||'unknown')}</b><span>site power state</span></div><div><b>${esc(entry?.power_source||'unknown')}</b><span>power source</span></div><div><b>${esc(entry?.ups_health||'unknown')}</b><span>UPS health</span></div><div><b>${esc(p.outage_started_at?ageText(p.outage_started_at):'—')}</b><span>confirmed outage age</span></div></div></section>`;}
function metricValue(v){if(!Number.isFinite(v))return'—';const a=Math.abs(v);if(a>=1e12)return`${(v/1e12).toFixed(2)}T`;if(a>=1e9)return`${(v/1e9).toFixed(2)}G`;if(a>=1e6)return`${(v/1e6).toFixed(2)}M`;if(a>=1e3)return`${(v/1e3).toFixed(2)}k`;return Number(v).toLocaleString(undefined,{maximumFractionDigits:2});}
function renderComponents(site,object){if(!object.components?.length)return'<section class="detail-section"><h3>Checks</h3><p class="component-meta">No direct checks.</p></section>';return`<section class="detail-section"><h3>Checks</h3><div class="component-list">${object.components.map(c=>`<div class="component-row"><div><strong>${esc(c.label||c.id)}</strong><div class="component-meta">${esc(c.adapter)} · ${esc(ageText(c.observed_at))}</div></div>${pill(c.state)}<p>${esc(c.summary)}</p>${Object.keys(c.metrics||{}).length?`<div class="metrics" style="grid-column:1/-1">${Object.entries(c.metrics).filter(([,v])=>Number.isFinite(v)).slice(0,6).map(([k,v])=>`<div class="metric"><b>${esc(metricValue(v))}</b><span>${esc(k.replaceAll('_',' '))}</span></div>`).join('')}</div>`:''}<button class="button secondary" data-run-check="${esc(c.id)}" type="button">Check now</button></div>`).join('')}</div></section>`;}
function renderActions(site,object){const custom=object.actions||[];return`<section class="detail-section"><h3>Actions</h3><div class="action-list"><button class="button" data-run-object type="button">Check object now</button>${custom.map(a=>`<button class="button secondary" data-action-id="${esc(a.id)}" type="button">${esc(a.label)}</button>`).join('')}${object.presentation_url?`<a class="button secondary" href="${esc(object.presentation_url)}" target="_blank" rel="noopener">Open service</a>`:''}</div></section>`;}
function renderCamera(site,object){if(app.cameraLive?.siteId===site.id&&app.cameraLive?.objectId===object.id)return`<section class="detail-section"><h3>Live camera</h3><div class="camera-preview"><video id="camera-live-video" autoplay muted playsinline controls></video><span id="camera-live-status" class="camera-status">${esc(app.cameraLive.message)}</span></div><div class="action-list" style="margin-top:.65rem"><button class="button secondary" data-live-stop type="button">Close live view</button></div><p class="component-meta" style="margin-top:.65rem">MonitorBox relays signaling only; WebRTC media remains browser ↔ Scrypted.</p></section>`;const snapshot=`/api/v2/cameras/${encodeURIComponent(site.id)}/${encodeURIComponent(object.id)}/snapshot?t=${Date.now()}`;return`<section class="detail-section"><h3>Camera</h3><div class="camera-preview"><img src="${snapshot}" alt="${esc(object.label)} snapshot"><span class="camera-status">On-demand snapshot</span></div><div class="action-list" style="margin-top:.65rem"><button class="button" data-live-start type="button">Open live view</button><button class="button secondary" data-refresh-snapshot type="button">Refresh snapshot</button></div></section>`;}
function bindDrawer(site,object){document.querySelectorAll('[data-run-check]').forEach(node=>node.onclick=()=>startOperation(`/api/v2/checks/${encodeURIComponent(site.id)}/${encodeURIComponent(node.dataset.runCheck)}/run`,node));document.querySelector('[data-run-object]')?.addEventListener('click',event=>startOperation(`/api/v2/objects/${encodeURIComponent(site.id)}/${encodeURIComponent(object.id)}/run`,event.currentTarget));document.querySelectorAll('[data-action-id]').forEach(node=>node.onclick=()=>startOperation(`/api/v2/actions/${encodeURIComponent(site.id)}/${encodeURIComponent(node.dataset.actionId)}`,node));document.querySelector('[data-live-start]')?.addEventListener('click',()=>startCameraLive(site.id,object.id));document.querySelector('[data-live-stop]')?.addEventListener('click',()=>stopCameraLive());document.querySelector('[data-refresh-snapshot]')?.addEventListener('click',()=>renderDrawer());}

async function startOperation(url,button){if(button)button.disabled=true;try{const operation=await api(url,{method:'POST',headers:{'Idempotency-Key':requestId()}});app.operation=operation;showOperation();await pollOperation(operation.id);await loadState({quiet:true});toast(operation.coalesced?'Joined work already running':'Fresh check completed');}catch(error){toast(`Operation failed: ${error.message}`);}finally{if(button)button.disabled=false;}}
function showOperation(){const node=$('#operation');node.classList.remove('hidden');$('#operation-title').textContent=app.operation?.kind==='check_all'?'Checking everything now':'Running fresh operation';$('#operation-copy').textContent='Cached state will not satisfy this request; waiting for fresh results.';}
async function pollOperation(id){for(let i=0;i<420;i++){const operation=await api(`/api/v2/operations/${encodeURIComponent(id)}`);app.operation=operation;showOperation();if(operation.status!=='running'){setTimeout(()=>$('#operation').classList.add('hidden'),1200);if(operation.status==='failed')throw new Error('one or more checks failed to execute');return operation;}await new Promise(r=>setTimeout(r,700));}throw new Error('operation status timed out');}

function metricUnit(name){const n=name.toLowerCase();if(n.includes('percent')||n.endsWith('_pct')||n.includes('charge')||n.includes('load'))return'%';if(n.includes('celsius')||n.endsWith('_c'))return'°C';if(n.includes('latency')||n.includes('_ms'))return'ms';if(n.includes('bytes'))return'bytes';if(n.includes('mbps'))return'Mb/s';return'';}
function graphNumber(value,unit){if(!Number.isFinite(value))return'—';if(unit==='bytes'){const units=['B','KiB','MiB','GiB','TiB'];let v=value,i=0;while(Math.abs(v)>=1024&&i<units.length-1){v/=1024;i++;}return`${v.toFixed(Math.abs(v)>=100?0:1)} ${units[i]}`;}return`${Number(value).toFixed(Math.abs(value)>=100?0:Math.abs(value)>=10?1:2)}${unit?` ${unit}`:''}`;}
function chart(name,points){const values=points.filter(p=>Number.isFinite(p.value));if(values.length<2)return'';const unit=metricUnit(name),current=values[values.length-1].value;let min=Math.min(...values.map(p=>p.value)),max=Math.max(...values.map(p=>p.value));if(unit==='%'&&min>=0&&max<=100){min=0;max=100;}else if(min===max){const pad=Math.max(Math.abs(max)*.1,1);min-=pad;max+=pad;}else{const pad=(max-min)*.08;min-=pad;max+=pad;}const W=640,H=210,left=68,right=626,top=12,bottom=178,x=i=>left+(right-left)*(i/Math.max(points.length-1,1)),y=v=>bottom-(bottom-top)*((v-min)/(max-min));let path='',area='';points.forEach((p,i)=>{if(!Number.isFinite(p.value)){path='';return;}const command=path?'L':'M';path+=`${command}${x(i).toFixed(1)},${y(p.value).toFixed(1)} `;});const first=values[0],last=values[values.length-1];if(path)area=`${path}L${x(points.length-1)},${bottom} L${left},${bottom} Z`;const grid=[0,.5,1].map(r=>{const value=max-(max-min)*r,yy=top+(bottom-top)*r;return`<line class="chart-grid" x1="${left}" x2="${right}" y1="${yy}" y2="${yy}"/><text class="chart-axis" x="58" y="${yy+4}" text-anchor="end">${esc(graphNumber(value,unit))}</text>`;}).join('');return`<article class="metric-chart"><div class="chart-headline"><strong>${esc(name.replaceAll('_',' '))}</strong><span>${esc(graphNumber(current,unit))}</span></div><div class="chart-wrap"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Recent ${esc(name)}"><g>${grid}</g><path class="chart-area" d="${area}"/><path class="chart-path" d="${path}"/><text class="chart-axis" x="${left}" y="202">${esc(ageText(first.time))}</text><text class="chart-axis" x="${right}" y="202" text-anchor="end">now</text></svg></div></article>`;}
async function loadCharts(site,object){const target=$('#history-charts');if(!target)return;const charts=[];for(const component of (object.components||[]).filter(c=>c.id&&!c.id.includes(':')).slice(0,8)){const keys=Object.entries(component.metrics||{}).filter(([,v])=>Number.isFinite(v)).map(([k])=>k).slice(0,3);if(!keys.length)continue;try{const data=await api(`/api/v2/history/${encodeURIComponent(site.id)}/${encodeURIComponent(component.id)}?limit=120`);for(const key of keys){const points=data.observations.map(o=>({time:o.observed_at,value:Number(o.metrics?.[key])}));const html=chart(key,points);if(html)charts.push(html);}}catch(_){}if(charts.length>=8)break;}if(target)target.innerHTML=charts.length?`<div style="display:grid;gap:.65rem">${charts.join('')}</div>`:'<div class="chart-empty">No numerical history is available yet.</div>';}

function cameraOptions(){return{userAgent:navigator.userAgent,capabilities:{audio:RTCRtpReceiver.getCapabilities?.('audio')||{},video:RTCRtpReceiver.getCapabilities?.('video')||{}},screen:{devicePixelRatio:devicePixelRatio,width:screen.width,height:screen.height}};}
function waitIceComplete(pc){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{const done=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',done);resolve();}};pc.addEventListener('icegatheringstatechange',done);});}
async function ensureCameraPeer(live,setup){if(live.pc)return live.pc;const pc=live.pc=new RTCPeerConnection(setup.configuration);const stream=new MediaStream();pc.ontrack=event=>{for(const track of event.streams[0]?.getTracks()||[event.track])if(!stream.getTracks().includes(track))stream.addTrack(track);const video=$('#camera-live-video');if(video){video.srcObject=stream;video.play().catch(()=>{});}};pc.oniceconnectionstatechange=()=>{if(['connected','completed'].includes(pc.iceConnectionState))setCameraStatus('Live');else if(['failed','disconnected','closed'].includes(pc.iceConnectionState))setCameraStatus('Playback connection lost');};if(setup.audio)pc.addTransceiver('audio',setup.audio);if(setup.video)pc.addTransceiver('video',setup.video);return pc;}
function setCameraStatus(message){if(!app.cameraLive)return;app.cameraLive.message=message;const node=$('#camera-live-status');if(node)node.textContent=message;}
async function handleCameraCall(live,message){const respond=(value,error)=>live.socket?.send(JSON.stringify({type:'result',callId:message.callId,value,error}));try{const [first,setup={}] = message.args||[],pc=await ensureCameraPeer(live,message.method==='createLocalDescription'?(message.args?.[1]||{}):setup);if(message.method==='createLocalDescription'){pc.onicecandidate=event=>{if(event.candidate&&message.trickle&&live.socket?.readyState===WebSocket.OPEN)live.socket.send(JSON.stringify({type:'candidate',callId:message.callId,candidate:event.candidate.toJSON?.()||event.candidate}));};let description=first==='offer'?await pc.createOffer({offerToReceiveAudio:!!setup.audio,offerToReceiveVideo:!!setup.video}):await pc.createAnswer();await pc.setLocalDescription(description);if(!message.trickle)await waitIceComplete(pc);description=pc.localDescription||description;respond({type:description.type,sdp:description.sdp});}else if(message.method==='setRemoteDescription'){await pc.setRemoteDescription(first);respond(null);}else if(message.method==='addIceCandidate'){await pc.addIceCandidate(first);respond(null);}else throw new Error('unsupported signaling operation');}catch(error){respond(null,error.message||'signaling failed');}}
function startCameraLive(siteId,objectId){if(app.cameraLive)return;const live=app.cameraLive={siteId,objectId,message:'Starting secure playback…',socket:null,pc:null};renderDrawer();const scheme=location.protocol==='https:'?'wss:':'ws:';const socket=live.socket=new WebSocket(`${scheme}//${location.host}/api/v2/cameras/${encodeURIComponent(siteId)}/${encodeURIComponent(objectId)}/live`);socket.onopen=()=>socket.send(JSON.stringify({type:'hello',options:cameraOptions()}));socket.onmessage=event=>{let message;try{message=JSON.parse(event.data);}catch{return;}if(message.type==='call')handleCameraCall(live,message);else if(message.type==='ready')setCameraStatus('Negotiating direct media…');else if(message.type==='error')setCameraStatus(message.error||'Playback failed');};socket.onerror=()=>setCameraStatus('Playback connection failed');socket.onclose=()=>{if(app.cameraLive===live)setCameraStatus('Playback ended');};}
function stopCameraLive(rerender=true){const live=app.cameraLive;if(!live)return;app.cameraLive=null;try{live.socket?.close(1000,'viewer closed');}catch(_){}if(live.pc){for(const receiver of live.pc.getReceivers())receiver.track?.stop();for(const sender of live.pc.getSenders())sender.track?.stop();live.pc.close();}const video=$('#camera-live-video');if(video?.srcObject)for(const track of video.srcObject.getTracks())track.stop();if(rerender&&app.selected)renderDrawer();}

$('#reload').onclick=async()=>{const node=$('#reload');node.disabled=true;try{await loadState();toast('Status reloaded');}finally{node.disabled=false;}};
$('#check-all').onclick=async()=>{const node=$('#check-all');node.disabled=true;try{const operation=await api('/api/v2/checks/run',{method:'POST'});app.operation=operation;showOperation();await pollOperation(operation.id);await loadState({quiet:true});toast('Fresh full monitoring pass complete');}catch(error){toast(`Full check failed: ${error.message}`);}finally{node.disabled=false;}};
$('#drawer-close').onclick=closeDrawer;
$('#drawer').addEventListener('click',event=>{if(event.target===$('#drawer'))closeDrawer();});
window.addEventListener('hashchange',()=>{if(!location.hash)return;const [siteId,objectId]=location.hash.slice(1).split('/').map(decodeURIComponent);if(siteId&&objectId)openDrawer(siteId,objectId);});
window.addEventListener('pageshow',event=>{if(event.persisted)loadState({quiet:true}).catch(()=>{});});
document.addEventListener('visibilitychange',()=>{clearInterval(app.poll);app.poll=setInterval(()=>loadState({quiet:true}).catch(()=>{}),document.hidden?60000:15000);if(document.hidden)stopCameraLive(false);});
loadState().then(()=>{if(location.hash){const [siteId,objectId]=location.hash.slice(1).split('/').map(decodeURIComponent);if(siteId&&objectId)openDrawer(siteId,objectId);}}).catch(()=>{});
app.poll=setInterval(()=>loadState({quiet:true}).catch(()=>{}),15000);
