'use strict';

const $=id=>document.getElementById(id);
let csrf=null,current=null,working=null,siteId=null,candidateId=null,resumeSetup=false;

async function api(url,options={}){
  options.headers={...(options.headers||{})};
  if(options.body&&!options.headers['Content-Type'])options.headers['Content-Type']='application/json';
  if(csrf&&options.method&&options.method!=='GET')options.headers['X-MonitorBox-CSRF']=csrf;
  const response=await fetch(url,options),text=await response.text();let body={};
  try{body=text?JSON.parse(text):{};}catch{body={error:text};}
  if(!response.ok)throw new Error(body.error||text||`HTTP ${response.status}`);
  return body;
}
function deep(value){return JSON.parse(JSON.stringify(value));}
function slug(value){let s=String(value||'item').toLowerCase().replace(/[^a-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'');if(!/^[a-z]/.test(s))s='item_'+s;return s.slice(0,64);}
function site(){return(working?.sites||[]).find(item=>item.id===siteId);}
function unique(prefix,items){let id=slug(prefix),n=2;const ids=new Set(items.map(item=>item.id));while(ids.has(id))id=`${slug(prefix)}_${n++}`;return id;}
function field(label,value,onchange,type='text'){const wrap=document.createElement('label');wrap.className='field';wrap.append(document.createTextNode(label));const input=document.createElement('input');input.type=type;input.value=value??'';input.onchange=()=>onchange(type==='number'?Number(input.value):input.value);wrap.append(input);return wrap;}
function selectField(label,value,choices,onchange){const wrap=document.createElement('label');wrap.className='field';wrap.append(document.createTextNode(label));const select=document.createElement('select');for(const choice of choices){const option=document.createElement('option');const item=typeof choice==='string'?{value:choice,label:choice}:choice;option.value=item.value;option.textContent=item.label;option.selected=String(item.value)===String(value??'');select.append(option);}select.onchange=()=>onchange(select.value);wrap.append(select);return wrap;}
function button(label,kind,onclick){const b=document.createElement('button');b.type='button';b.className=`button ${kind||''}`.trim();b.textContent=label;b.onclick=onclick;return b;}
function objectChoices(currentSite){return(currentSite.objects||[]).map(o=>({value:o.id,label:`${o.label||o.id} · ${o.kind}`}));}
function agentChoices(currentSite){return(currentSite.agents||[]).map(a=>({value:a.id,label:a.label||a.id}));}
function providerCheckId(object,capability,provider){return String(provider.check_id||`${object.id}_${capability.id}_${provider.id}`);}
function checks(currentSite){const result=[];for(const object of currentSite.objects||[])for(const capability of object.capabilities||[])for(const provider of capability.providers||[]){const checkId=providerCheckId(object,capability,provider);result.push({id:checkId,label:String(provider.label||capability.label||checkId),object_id:object.id,object_label:object.label||object.id,adapter:String(provider.adapter||'')});}return result;}
function hostEligibleChecks(currentSite,objectId){const eligible=new Set([objectId]);for(const object of currentSite.objects||[])if((object.depends_on||[]).includes(objectId))eligible.add(object.id);return checks(currentSite).filter(item=>eligible.has(item.object_id));}
function guessAddress(currentSite,objectId){return String((currentSite.objects||[]).find(o=>o.id===objectId)?.address||'');}

async function authenticate(){try{const status=await api('/api/v2/config/status');resumeSetup=status.setup_complete===false;if(status.authenticated){csrf=(await api('/api/v2/config/session')).csrf_token;await load();return;}$('login').classList.remove('hidden');$('app').classList.add('hidden');}catch(error){$('loginStatus').textContent=error.message;}}
$('loginButton').onclick=async()=>{try{const body=await api('/api/v2/config/auth/login',{method:'POST',body:JSON.stringify({password:$('password').value})});csrf=body.csrf_token;$('login').classList.add('hidden');await load();}catch(error){$('loginStatus').textContent=error.message;}};
async function load(){const payload=await api(resumeSetup?'/api/v2/config/setup/draft':'/api/v2/config/current');current=payload.config;working=deep(current);$('revision').textContent=resumeSetup?`Setup Draft · bootstrap revision ${payload.base_revision}`:`revision ${payload.revision}`;const sites=working.sites||[];$('siteSelect').replaceChildren();for(const item of sites){const option=document.createElement('option');option.value=item.id;option.textContent=item.label||item.id;$('siteSelect').append(option);}siteId=sites.some(item=>item.id===siteId)?siteId:sites[0]?.id;$('siteSelect').value=siteId||'';$('login').classList.add('hidden');$('app').classList.remove('hidden');render();}
$('siteSelect').onchange=()=>{siteId=$('siteSelect').value;render();};$('reload').onclick=()=>load();
function render(){renderActions();renderLifecycle();renderPower();}

function addAction(kind){const s=site();if(!s)return;s.actions=s.actions||[];const object=(s.objects||[]).find(o=>o.kind==='host')||s.objects?.[0];if(!object)return;const id=unique(kind==='wol'?`wake_${object.id}`:`ping_${object.id}`,s.actions);const common={id,object_id:object.id,agent:s.agents?.[0]?.id||'',kind,label:kind==='wol'?'Wake':'Continuous ping'};common.config=kind==='wol'?{host:guessAddress(s,object.id),mac_addresses:[],broadcast_address:'255.255.255.255',timeout_seconds:300,retry_seconds:30,probe_timeout_seconds:2}:{host:guessAddress(s,object.id),count:1,timeout_seconds:2,live_interval_seconds:1};s.actions.push(common);renderActions();}
$('addWol').onclick=()=>addAction('wol');$('addPing').onclick=()=>addAction('ping');
function renderActions(){const root=$('actions');root.replaceChildren();const s=site();if(!s)return;for(const action of s.actions||[]){const card=document.createElement('div');card.className='subcard';const head=document.createElement('div');head.className='section-head';const title=document.createElement('h4');title.textContent=action.label||action.id;head.append(title);const space=document.createElement('span');space.className='spacer';head.append(space);head.append(button('Remove','danger',()=>{s.actions=s.actions.filter(item=>item!==action);renderActions();}));card.append(head);const grid=document.createElement('div');grid.className='grid';grid.append(field('ID',action.id,()=>{},'text'),field('Label',action.label,v=>{action.label=v;renderActions();}),selectField('Kind',action.kind,[{value:'wol',label:'Wake-on-LAN'},{value:'ping',label:'Continuous ping'}],v=>{if(v===action.kind)return;action.kind=v;action.config=v==='wol'?{host:guessAddress(s,action.object_id),mac_addresses:[],broadcast_address:'255.255.255.255',timeout_seconds:300,retry_seconds:30,probe_timeout_seconds:2}:{host:guessAddress(s,action.object_id),count:1,timeout_seconds:2,live_interval_seconds:1};renderActions();}),selectField('Object',action.object_id,objectChoices(s),v=>{action.object_id=v;if(!action.config?.host)action.config.host=guessAddress(s,v);renderActions();}),selectField('Agent',action.agent,agentChoices(s),v=>action.agent=v));card.append(grid);const config=document.createElement('div');config.className='grid';config.style.marginTop='10px';action.config=action.config||{};config.append(field(action.kind==='wol'?'Wake verification host / IP':'Ping target host / IP',action.config.host,v=>action.config.host=v));if(action.kind==='wol'){config.append(field('Wake target MAC addresses (comma separated)',(action.config.mac_addresses||[]).join(', '),v=>action.config.mac_addresses=v.split(',').map(x=>x.trim()).filter(Boolean)),field('Broadcast address',action.config.broadcast_address??'255.255.255.255',v=>action.config.broadcast_address=v),field('Overall timeout (s)',action.config.timeout_seconds??300,v=>action.config.timeout_seconds=v,'number'),field('Retry every (s)',action.config.retry_seconds??30,v=>action.config.retry_seconds=v,'number'),field('Probe timeout (s)',action.config.probe_timeout_seconds??2,v=>action.config.probe_timeout_seconds=v,'number'));}else{config.append(field('Ping count',action.config.count??1,v=>action.config.count=v,'number'),field('Ping timeout (s)',action.config.timeout_seconds??2,v=>action.config.timeout_seconds=v,'number'),field('Live interval (s)',action.config.live_interval_seconds??1,v=>action.config.live_interval_seconds=v,'number'));}card.append(config);root.append(card);}if(!(s.actions||[]).length){const p=document.createElement('p');p.className='muted';p.textContent='No actions configured for this site.';root.append(p);}}

$('addLifecycle').onclick=()=>{const s=site();if(!s)return;s.lifecycle=s.lifecycle||[];const used=new Set(s.lifecycle.map(item=>item.object_id));const object=(s.objects||[]).find(o=>o.kind==='host'&&!used.has(o.id))||(s.objects||[]).find(o=>!used.has(o.id));if(!object)return;const eligible=hostEligibleChecks(s,object.id),reach=eligible.find(item=>item.adapter==='icmp')||eligible[0];s.lifecycle.push({object_id:object.id,reachability_check:reach?.id||'',recovery_checks:reach?[reach.id]:[],reboot_timeout_seconds:600,shutdown_timeout_seconds:1800});renderLifecycle();};
function renderLifecycle(){const root=$('lifecycle');root.replaceChildren();const s=site();if(!s)return;for(const policy of s.lifecycle||[]){const eligible=hostEligibleChecks(s,policy.object_id);const card=document.createElement('div');card.className='subcard';const head=document.createElement('div');head.className='section-head';const title=document.createElement('h4');title.textContent=`${(s.objects||[]).find(o=>o.id===policy.object_id)?.label||policy.object_id} lifecycle`;head.append(title);const space=document.createElement('span');space.className='spacer';head.append(space);head.append(button('Remove','danger',()=>{s.lifecycle=s.lifecycle.filter(item=>item!==policy);renderLifecycle();}));card.append(head);const grid=document.createElement('div');grid.className='grid';grid.append(selectField('Object',policy.object_id,objectChoices(s),v=>{policy.object_id=v;const next=hostEligibleChecks(s,v);const reach=next.find(item=>item.adapter==='icmp')||next[0];policy.reachability_check=reach?.id||'';policy.recovery_checks=reach?[reach.id]:[];renderLifecycle();}),selectField('Ping / readiness check',policy.reachability_check,eligible.map(item=>({value:item.id,label:`${item.label} · ${item.id}`})),v=>policy.reachability_check=v),field('Reboot / wake timeout (s)',policy.reboot_timeout_seconds??600,v=>policy.reboot_timeout_seconds=v,'number'),field('Shutdown timeout (s)',policy.shutdown_timeout_seconds??1800,v=>policy.shutdown_timeout_seconds=v,'number'));card.append(grid);const label=document.createElement('div');label.className='eyebrow';label.style.marginTop='12px';label.textContent='Recovery evidence';card.append(label);const list=document.createElement('div');list.className='checks';const selected=new Set(policy.recovery_checks||[]);for(const item of eligible){const row=document.createElement('label');row.className='check';const input=document.createElement('input');input.type='checkbox';input.checked=selected.has(item.id);input.onchange=()=>{const values=new Set(policy.recovery_checks||[]);if(input.checked)values.add(item.id);else values.delete(item.id);policy.recovery_checks=eligible.filter(candidate=>values.has(candidate.id)).map(candidate=>candidate.id);};const text=document.createElement('span');text.textContent=`${item.label} · ${item.id}`;row.append(input,text);list.append(row);}card.append(list);root.append(card);}if(!(s.lifecycle||[]).length){const p=document.createElement('p');p.className='muted';p.textContent='No lifecycle policy configured for this site.';root.append(p);}}

function renderPower(){const root=$('power');root.replaceChildren();const s=site();if(!s)return;s.power=s.power||{};const inventory=checks(s),ups=inventory.filter(item=>item.adapter==='nut'||(s.objects||[]).find(o=>o.id===item.object_id)?.kind==='ups');const selected=new Set(s.power.ups_checks||[]);const grid=document.createElement('div');grid.className='grid';grid.append(field('Confirm outage window (s)',s.power.confirm_window_seconds??15,v=>s.power.confirm_window_seconds=v,'number'),selectField('Primary UPS check',s.power.primary_ups_check??'',[{value:'',label:'None'},...ups.map(item=>({value:item.id,label:`${item.label} · ${item.id}`}))],v=>{if(v)s.power.primary_ups_check=v;else delete s.power.primary_ups_check;}));root.append(grid);const heading=document.createElement('div');heading.className='eyebrow';heading.style.marginTop='12px';heading.textContent='UPS checks participating in power policy';root.append(heading);const list=document.createElement('div');list.className='checks';for(const item of ups){const row=document.createElement('label');row.className='check';const input=document.createElement('input');input.type='checkbox';input.checked=selected.has(item.id);input.onchange=()=>{const values=new Set(s.power.ups_checks||[]);if(input.checked)values.add(item.id);else values.delete(item.id);s.power.ups_checks=ups.filter(candidate=>values.has(candidate.id)).map(candidate=>candidate.id);if(s.power.primary_ups_check&&!values.has(s.power.primary_ups_check))delete s.power.primary_ups_check;renderPower();};row.append(input,document.createTextNode(`${item.label} · ${item.id}`));list.append(row);}if(!ups.length)list.textContent='No NUT/UPS checks are currently configured.';root.append(list);const thresholdTitle=document.createElement('div');thresholdTitle.className='eyebrow';thresholdTitle.style.marginTop='14px';thresholdTitle.textContent='Protective timing by host (seconds)';root.append(thresholdTitle);s.power.protective_thresholds=s.power.protective_thresholds||{};const thresholdGrid=document.createElement('div');thresholdGrid.className='grid';for(const object of (s.objects||[]).filter(o=>o.kind==='host'))thresholdGrid.append(field(object.label||object.id,s.power.protective_thresholds[object.id]??'',v=>{if(v===''||!Number.isFinite(Number(v))||Number(v)<=0)delete s.power.protective_thresholds[object.id];else s.power.protective_thresholds[object.id]=Number(v);},'number'));root.append(thresholdGrid);}

$('validate').onclick=async()=>{try{const prepared=await api(resumeSetup?'/api/v2/config/setup/preview':'/api/v2/config/candidates',{method:'POST',body:JSON.stringify({config:working})});candidateId=prepared.candidate_id;$('previewSummary').className='status good';$('previewSummary').textContent=`${prepared.preview.summary.added} added · ${prepared.preview.summary.modified} modified · ${prepared.preview.summary.removed} removed`;$('previewChanges').textContent=JSON.stringify(prepared.preview.changes,null,2);$('apply').textContent=resumeSetup?'Add to Setup Draft':'Apply configuration';$('apply').disabled=false;$('preview').showModal();}catch(error){alert(`Validation failed: ${error.message}`);}};
$('closePreview').onclick=()=>$('preview').close();$('apply').onclick=async()=>{try{if(!candidateId)return;$('apply').disabled=true;if(resumeSetup){const staged=await api(`/api/v2/config/setup/preview/${candidateId}/stage`,{method:'POST'});$('previewSummary').textContent=`Added to Setup Draft. ${staged.cumulative_preview.summary.added} added · ${staged.cumulative_preview.summary.modified} modified · ${staged.cumulative_preview.summary.removed} removed versus bootstrap.`;setTimeout(()=>location.href='/settings',700);return}const applied=await api(`/api/v2/config/candidates/${candidateId}/apply`,{method:'POST'});$('previewSummary').textContent=`Revision ${applied.revision} applied. ${applied.runtime_reconcile}.`;setTimeout(()=>location.href='/',1000);}catch(error){$('previewSummary').className='status bad';$('previewSummary').textContent=error.message;$('apply').disabled=false;}};
authenticate();